export const CREATE_FIR_REQUEST = 'CREATE_FIR_REQUEST';
export const CREATE_FIR_SUCCESS = 'CREATE_FIR_SUCCESS';
export const CREATE_FIR_FAILURE = 'CREATE_FIR_FAILURE';

export const GET_FIR_BY_ID_REQUEST = 'GET_FIR_BY_ID_REQUEST';
export const GET_FIR_BY_ID_SUCCESS = 'GET_FIR_BY_ID_SUCCESS';
export const GET_FIR_BY_ID_FAILURE = 'GET_FIR_BY_ID_FAILURE';

export const GET_FIRS_REQUEST = 'GET_FIRS_REQUEST';
export const GET_FIRS_SUCCESS = 'GET_FIRS_SUCCESS';
export const GET_FIRS_FAILURE = 'GET_FIRS_FAILURE';

export const UPDATE_FIR_REQUEST = 'UPDATE_FIR_REQUEST';
export const UPDATE_FIR_SUCCESS = 'UPDATE_FIR_SUCCESS';
export const UPDATE_FIR_FAILURE = 'UPDATE_FIR_FAILURE';

export const DELETE_FIR_REQUEST = 'DELETE_FIR_REQUEST';
export const DELETE_FIR_SUCCESS = 'DELETE_FIR_SUCCESS';
export const DELETE_FIR_FAILURE = 'DELETE_FIR_FAILURE';
