export const CREATE_CRIMINAL_REQUEST = 'CREATE_CRIMINAL_REQUEST';
export const CREATE_CRIMINAL_SUCCESS = 'CREATE_CRIMINAL_SUCCESS';
export const CREATE_CRIMINAL_FAILURE = 'CREATE_CRIMINAL_FAILURE';

export const GET_CRIMINAL_BY_ID_REQUEST = 'GET_CRIMINAL_BY_ID_REQUEST';
export const GET_CRIMINAL_BY_ID_SUCCESS = 'GET_CRIMINAL_BY_ID_SUCCESS';
export const GET_CRIMINAL_BY_ID_FAILURE = 'GET_CRIMINAL_BY_ID_FAILURE';


export const GET_CRIMINALS_REQUEST = 'GET_CRIMINALS_REQUEST';
export const GET_CRIMINALS_SUCCESS = 'GET_CRIMINALS_SUCCESS';
export const GET_CRIMINALS_FAILURE = 'GET_CRIMINALS_FAILURE';


export const UPDATE_CRIMINAL_REQUEST = 'UPDATE_CRIMINAL_REQUEST';
export const UPDATE_CRIMINAL_SUCCESS = 'UPDATE_CRIMINAL_SUCCESS';
export const UPDATE_CRIMINAL_FAILURE = 'UPDATE_CRIMINAL_FAILURE';

export const DELETE_CRIMINAL_REQUEST = 'DELETE_CRIMINAL_REQUEST';
export const DELETE_CRIMINAL_SUCCESS = 'DELETE_CRIMINAL_SUCCESS';
export const DELETE_CRIMINAL_FAILURE = 'DELETE_CRIMINAL_FAILURE';