export const CREATE_COURT_REQUEST = 'CREATE_COURT_REQUEST';
export const CREATE_COURT_SUCCESS = 'CREATE_COURT_SUCCESS';
export const CREATE_COURT_FAILURE = 'CREATE_COURT_FAILURE';

export const GET_COURT_BY_ID_REQUEST = 'GET_COURT_BY_ID_REQUEST';
export const GET_COURT_BY_ID_SUCCESS = 'GET_COURT_BY_ID_SUCCESS';
export const GET_COURT_BY_ID_FAILURE = 'GET_COURT_BY_ID_FAILURE';

export const GET_COURTS_REQUEST = 'GET_COURTS_REQUEST';
export const GET_COURTS_SUCCESS = 'GET_COURTS_SUCCESS';
export const GET_COURTS_FAILURE = 'GET_COURTS_FAILURE';

export const UPDATE_COURT_REQUEST = 'UPDATE_COURT_REQUEST';
export const UPDATE_COURT_SUCCESS = 'UPDATE_COURT_SUCCESS';
export const UPDATE_COURT_FAILURE = 'UPDATE_COURT_FAILURE';

export const DELETE_COURT_REQUEST = 'DELETE_COURT_REQUEST';
export const DELETE_COURT_SUCCESS = 'DELETE_COURT_SUCCESS';
export const DELETE_COURT_FAILURE = 'DELETE_COURT_FAILURE';
